#
# This workflow will run all dotnet integrations tests.
#

name: dotnet-integration-tests-processes

on:
  push:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
  merge_group:
    branches: ["main"]

permissions:
  contents: read

jobs:
  integration-tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        configuration: [Debug]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Cache .NET packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Find projects
        shell: bash
        run: echo "projects=$(find ./dotnet -type f -name "Process.IntegrationTestRunner.*.csproj" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Set up Dapr
        uses: dapr/setup-dapr@v1
        with:
          dapr-version: "1.14.1"

      - name: Verify Dapr installation
        run: dapr --version

      - name: Initialize Dapr runtime
        run: dapr init

      - name: Install systemd
        run: sudo apt-get update && sudo apt-get install -y systemd

      - name: Start systemd
        run: sudo systemctl start systemd

      - name: Verify systemd status
        run: sudo systemctl status systemd

      - name: Process Integration Tests
        shell: bash
        env:
          AzureOpenAI__Label: azure-text-davinci-003
          AzureOpenAIEmbedding__Label: azure-text-embedding-ada-002
          AzureOpenAI__DeploymentName: ${{ vars.AZUREOPENAI__DEPLOYMENTNAME }}
          AzureOpenAIEmbeddings__DeploymentName: ${{ vars.AZUREOPENAIEMBEDDING__DEPLOYMENTNAME }}
          AzureOpenAI__Endpoint: ${{ secrets.AZUREOPENAI__ENDPOINT }}
          AzureOpenAIEmbeddings__Endpoint: ${{ secrets.AZUREOPENAI__ENDPOINT }}
          AzureOpenAI__ApiKey: ${{ secrets.AZUREOPENAI__APIKEY }}
          AzureOpenAIEmbeddings__ApiKey: ${{ secrets.AZUREOPENAI__APIKEY }}
          Bing__ApiKey: ${{ secrets.BING__APIKEY }}
          OpenAI__ApiKey: ${{ secrets.OPENAI__APIKEY }}
        run: |
          for project in ${{ env.projects }}; do
            dotnet test $project --verbosity normal --logger trx --results-directory ./TestResults --configuration ${{ matrix.configuration }}
          done

      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-testresults-${{ matrix.configuration }}
          path: ./TestResults
        if: always()

      - name: Fix Errors
        if: failure()
        run: |
          chmod +x ./fix-errors.sh
          ./fix-errors.sh

      - name: Log Error Message
        if: failure()
        run: echo "Error occurred during the integration tests process"
